### PR TITLE
This is a engine so rails must be defined

### PR DESCRIPTION
**Pull request by dixpac**
This is a engine so we don't need to check weather `rails` is defined.

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Though it depends on other Rails components, Active Storage can theoretically be used outside of a Rails app.

**Comment by dhh** [comment]
George, I actually just added Rails as a dependency. I don't think there's any framework that we're not using at this point! But open to that discussion.

I do think, though, that we'll want to move closer to a standard engine with a dummy app in order to get testing going without the hoops. I did a bunch of stuff in the test_helper.rb to make things work without running like a real engine. Doesn't seem worth it.

**Comment by dixpac** [comment]
Yes reason why I removed this was because @dhh  start moved this to the engine conventions. If this is going to be a engine I think that using dummy for app for the testing would be the best choice. 
For example: converting these controller tests to integration tests(since controller tests are deprecated) will be a hassle without the dummy

I did try to play with using some kind of slimmed down dummy rails app but at the end not sure that it's worth the hacking :)

**Comment by dhh** [comment]
Dino, yeah, let's just move to the standard conventions for engines and
test.

**Pull request merged**
