### PR TITLE
Add railtie support for configuring Mirror service

### PR DESCRIPTION
**Pull request by ffmike**
Here's a crack at fixing #9 

I do not immediately see how to modify the tests to verify the correct behavior; currently there is no test coverage for the railtie. But this works fine in my sample project.

Also not entirely convinced I've nailed the naming. I did change the key in the configuration file because I'm not comfortable with "service" and "services" right next to each other - seems like an invitation to errors.

### CODE REVIEW

**Comment by dhh** [comment]
I like this direction, @ffmike. What's clear though is that the railtie is now doing too much work itself. We should extract a ActiveStorage::Configuration object that can do the actual loading work. Then we can use Compose Method to clarify what's going on and slim it down. AND then we can more easily test things than going through railtie testing. Want to take a crack at that?

**Comment by ffmike** [comment]
Slammed today, might take a crack at it over the weekend if no one beats me to it.

**Comment by dhh** [comment]
👌

**Comment by jeremy** [comment]
Did something similar in #23! Key bit is a build step that concrete services can use to configure additional sub-services before instantiating themselves.

**Comment by ffmike** [comment]
I love open source. Things get fixed while I'm out kayaking. Thanks all!

**Pull request closed without merging**
