### PR TITLE
Basic routing tests

### PR DESCRIPTION
**Pull request by dixpac**
Since the routes are part of the "public api", these PR test that we
match requests to the right controller, action, ....

### CODE REVIEW

**Comment by dhh** [comment]
Hey, I'd rather just test these through integration tests that actually hit the controllers by calling the real routes. Happy to see a stab taken at converting the controller tests we have to integration tests instead.

**Comment by dixpac** [comment]
@dhh That makes sense. I started working on moving the gem to engine conventions and there I successfully converted controller tests to integration tests. Didn't yet submit that PR because I'm not sure wether my approach makes sense, pls have a look when you have some free time, would love to hear from wether moving this to engine is correct approach
[Commit](https://github.com/dixpac/activestorage/commit/f4ff506b5e73d2f4394c94d2f320d923147ed893)

**Comment by dhh** [comment]
Yeah, definitely keen to move everything into the engine locations and take
advantage of that automation. The dummy app seems pretty substantial in
that commit. Could we slim that down?

**Comment by dixpac** [comment]
👍 I think that we can, since we don't need the whole rails for it. We could also use this dummy to test the engine more easily also, multiple attachments, etc...

**Comment by dixpac** [comment]
I will open PR then in the next few days so we can discuss there 😃

**Pull request closed without merging**
